/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 79
#define YY_END_OF_BUFFER 80
static yyconst short int yy_acclist[480] =
    {   0,
       80,   78,   79,   77,   78,   79,   77,   79,   65,   78,
       79,   78,   79,   65,   78,   79,   78,   79,   61,   78,
       79,   65,   78,   79,   65,   78,   79,   65,   78,   79,
       65,   78,   79,   57,   78,   79,   61,   78,   79,   65,
       78,   79,   65,   78,   79,   65,   78,   79,   78,   79,
       78,   79,   55,   78,   79,   55,   78,   79,   55,   78,
       79,   55,   78,   79,   55,   78,   79,   55,   78,   79,
       55,   78,   79,   55,   78,   79,   55,   78,   79,   55,
       78,   79,   55,   78,   79,   55,   78,   79,   55,   78,
       79,   55,   78,   79,   55,   78,   79,   55,   78,   79,

       55,   78,   79,   55,   78,   79,   72,   60,   58,   58,
       58,   66,   68,   63,   75,   74,   57,   62,   69,   67,
       71,   64,   70,   73,   57,   58,   55,   55,   55,   55,
       55,   55,   55,   55,   16,   55,   55,   55,   21,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   51,   55,
       55,   55,   60,   59,   58,   58,   75,   75,   57,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,

       55,   55,   55,   55,   55,   55,   55,   49,   55,   55,
       55,   55,   55,   56,   60,   56,   56,   76,   57,   55,
       55,   55,   55,   55,   55,   55,    6,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   37,   55,   55,   39,   55,   55,   55,   55,
       55,   55,   45,   55,   55,   55,   55,   55,   52,   55,
       53,   55,   55,   55,   55,   55,   55,   55,   55,   18,
       55,    8,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   27,   55,   55,

       55,   31,   55,   55,   55,   34,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   48,   55,   55,
       55,   55,   55,   55,   55,    5,   55,   55,   55,   55,
       55,   13,   55,   11,   55,   55,   55,   55,   55,   55,
       22,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       33,   55,   55,   55,   55,   55,   41,   55,   55,   55,
       55,   55,   47,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   20,   55,   55,
       55,   55,   25,   55,   26,   55,   55,   29,   55,   55,
       55,   55,   55,   38,   55,   40,   55,   55,   55,   44,

       55,   55,   55,   55,   55,   55,    3,   55,    4,   55,
        7,   55,    9,   55,   55,   55,   55,   55,   17,   55,
       19,   55,   23,   55,   55,   55,   30,   55,   32,   55,
       35,   55,   55,   55,   43,   55,   46,   55,   55,   54,
       55,    1,   55,   55,   10,   55,   55,   55,   55,   55,
       55,   55,   55,   55,    2,   55,   55,   55,   15,   55,
       24,   55,   28,   55,   55,   55,   55,   12,   55,   14,
       55,   36,   55,   55,   50,   55,   55,   42,   55
    } ;

static yyconst short int yy_accept[415] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   12,   14,   17,
       19,   22,   25,   28,   31,   34,   37,   40,   43,   46,
       49,   51,   53,   56,   59,   62,   65,   68,   71,   74,
       77,   80,   83,   86,   89,   92,   95,   98,  101,  104,
      107,  108,  108,  109,  109,  109,  109,  109,  109,  109,
      110,  111,  112,  112,  113,  114,  115,  115,  116,  117,
      117,  118,  118,  119,  120,  121,  122,  123,  124,  125,
      126,  126,  126,  127,  128,  129,  130,  131,  132,  133,
      134,  135,  137,  138,  139,  141,  142,  143,  144,  145,
      146,  147,  148,  149,  150,  151,  152,  153,  154,  155,

      156,  157,  158,  159,  161,  162,  163,  163,  164,  164,
      164,  164,  164,  164,  164,  164,  165,  166,  167,  167,
      167,  167,  167,  167,  168,  169,  170,  171,  172,  173,
      174,  175,  176,  177,  178,  179,  180,  181,  182,  183,
      184,  185,  186,  187,  188,  189,  190,  191,  192,  193,
      194,  195,  196,  197,  198,  199,  200,  201,  202,  203,
      204,  205,  206,  207,  208,  210,  211,  212,  213,  214,
      216,  217,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  219,  220,  221,
      222,  223,  224,  225,  226,  227,  229,  230,  231,  232,

      233,  234,  235,  236,  237,  238,  239,  240,  241,  242,
      243,  244,  245,  246,  247,  248,  249,  250,  251,  252,
      253,  255,  256,  258,  259,  260,  261,  262,  263,  265,
      266,  267,  268,  269,  271,  273,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  275,  276,
      277,  278,  279,  280,  282,  284,  285,  286,  287,  288,
      289,  290,  291,  292,  293,  294,  295,  296,  297,  298,
      300,  301,  302,  304,  305,  306,  308,  309,  310,  311,
      312,  313,  314,  315,  316,  317,  318,  320,  321,  322,
      322,  322,  322,  323,  324,  325,  326,  328,  329,  330,

      331,  332,  334,  336,  337,  338,  339,  340,  341,  343,
      344,  345,  346,  347,  348,  349,  350,  351,  353,  354,
      355,  356,  357,  359,  360,  361,  362,  363,  365,  366,
      367,  368,  369,  370,  371,  372,  373,  374,  375,  376,
      377,  378,  380,  381,  382,  383,  385,  387,  388,  390,
      391,  392,  393,  394,  396,  398,  399,  400,  402,  403,
      404,  405,  406,  407,  409,  411,  413,  415,  416,  417,
      418,  419,  421,  423,  425,  426,  427,  429,  431,  433,
      434,  435,  437,  439,  440,  442,  444,  445,  447,  448,
      449,  450,  451,  452,  453,  454,  455,  457,  458,  459,

      461,  463,  465,  466,  467,  468,  470,  472,  474,  475,
      477,  478,  480,  480
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
        9,   10,   11,    9,   12,   13,   14,   15,   15,   15,
       16,   17,   17,   18,   18,   19,   19,   20,    9,   21,
       22,   23,   24,   25,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   30,   41,   42,   43,   44,   45,
       46,   47,   48,   49,   50,   51,   30,   52,   30,   53,
       26,   27,   28,   29,   30,    1,   31,   32,   33,   34,

       35,   36,   37,   38,   39,   40,   30,   41,   42,   43,
       44,   45,   46,   47,   48,   49,   50,   51,   30,   52,
       30,   53,    9,    9,    9,   54,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[55] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    1,    1,
        1,    1,    1,    1,    5,    5,    5,    5,    6,    1,
        1,    1,    1,    7,    1,    1,    8,    1,    1,    9,
        5,    5,    6,    6,    6,    5,    9,    9,    9,    9,
        9,    9,   10,    9,    9,    9,   10,    9,   10,    9,
       10,   10,    9,    1
    } ;

static yyconst short int yy_base[428] =
    {   0,
        0,    0,  830,  831,  831,  831,  807,   50,  831,   41,
      831,  818,  804,  813,   59,   63,   50,  813,   53,  802,
       73,   82,    0,   63,  779,   65,  787,   62,   68,  786,
      789,  776,   44,   69,  769,   73,  782,   91,  777,  784,
      831,  112,  831,  116,  129,  133,  142,  146,  806,  157,
      162,  177,  172,  831,  831,  831,  803,  809,  831,  184,
      196,  211,  831,  831,  831,  831,  831,  831,  831,  192,
        0,  201,  216,    0,  763,  766,  765,  120,  777,  764,
       81,  188,  771,  770,  755,  758,  769,  108,  758,  757,
      751,  749,  754,  748,  760,  760,  746,   15,  127,  760,

      206,  750,  207,  747,  744,  741,  237,  782,  781,  242,
      255,  280,  260,  275,    0,  831,  318,  323,  302,  338,
        0,  775,  230,  781,  780,    0,  733,  748,  739,  744,
      743,  105,  733,  728,  157,  732,  727,   86,  729,  739,
      729,  211,  735,  734,  730,  736,  733,  730,  715,  728,
      709,  712,  717,  720,  714,  707,  725,  704,  268,  713,
      712,  713,  712,  711,    0,  710,  704,  703,  707,  740,
      739,  298,  343,  357,  380,  361,  375,  402,  416,  419,
      422,  445,  436,  735,  734,  314,  831,    0,  694,  701,
      704,  705,  694,  703,  704,    0,  699,  683,  683,  697,

      685,  694,  681,  686,  676,  690,  677,  680,  689,  676,
      685,  678,  679,  670,  668,  627,  640,  635,  614,  614,
        0,  611,    0,  614,  608,  601,  588,  595,    0,  581,
      577,  577,  576,    0,    0,  589,  477,  481,  495,  501,
      515,  519,  542,  440,  536,  565,  610,  586,  585,  584,
      579,  582,  559,    0,    0,  564,  237,  560,  557,  553,
      541,  538,  539,  542,  540,  546,  533,  522,  521,  525,
      521,  525,    0,  526,  509,    0,  508,  515,  500,  514,
      498,  510,  509,  505,  488,  498,    0,  479,  494,  578,
      582,  595,  488,  466,  471,  460,    0,  467,  442,  447,

      438,    0,    0,  453,  451,  448,  444,  425,    0,  438,
      435,  426,  425,  433,  423,  432,  428,    0,  427,  415,
      412,  398,    0,  402,  398,  386,  381,    0,  394,  384,
      374,  383,  366,  378,  361,  362,  356,  371,  368,  352,
      353,    0,  350,  341,  348,    0,    0,  343,    0,  339,
      329,  323,  338,    0,    0,  326,  333,    0,  319,  316,
      315,  305,  294,    0,    0,    0,    0,  309,  294,  287,
      277,    0,    0,    0,  276,  259,    0,    0,    0,  267,
      255,    0,    0,  250,    0,    0,  255,    0,  237,  225,
      226,  223,  227,  215,  213,  208,    0,  174,  149,    0,

        0,    0,  148,  139,  111,    0,    0,    0,   36,    0,
       40,    0,  831,  622,  632,  638,  648,  657,  665,  675,
      685,  691,  697,  703,  705,  707,  710
    } ;

static yyconst short int yy_def[428] =
    {   0,
      413,    1,  413,  413,  413,  413,  413,  414,  413,  415,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      413,  414,  413,  417,  417,  414,  414,  418,  413,  413,
      413,  413,  419,  413,  413,  413,  420,  421,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      422,  413,  413,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,

      416,  416,  416,  416,  416,  416,  417,  423,  423,  417,
      417,  423,  414,  414,  424,  413,  413,  413,  413,  413,
      425,  420,  420,  421,  413,  426,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  423,
      423,  417,  417,  417,  423,  414,  414,  414,  414,  414,
      414,  414,  413,  413,  427,  420,  413,  426,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,

      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  417,  417,  417,  417,
      417,  417,  417,  414,  414,  414,  413,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  417,
      417,  417,  416,  416,  416,  416,  416,  416,  416,  416,

      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,

      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,    0,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413
    } ;

static yyconst short int yy_nxt[886] =
    {   0,
        4,    5,    6,    7,    8,    9,    9,   10,   11,   12,
        9,   13,   14,   15,   16,   16,   16,   16,   16,   17,
       18,   19,   20,    4,    9,    9,   21,    9,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   23,
       33,   34,   23,   35,   36,   23,   37,   38,   39,   23,
       40,   23,   23,    9,   43,   50,   51,   51,   52,   52,
      156,  157,   44,   45,   46,   47,   47,   53,   57,   63,
       60,   64,   58,   66,   93,   67,   48,   61,   61,   61,
       61,   61,   94,  412,  411,   59,   69,   70,   70,   70,
       70,   62,   72,   72,   75,   78,   73,   73,   73,   73,

       73,   83,   84,   98,   85,   79,   88,   95,   80,   86,
       76,  136,   96,   87,   81,  137,   43,   89,  202,   99,
      108,  102,  100,  109,   71,  103,   46,   47,   47,  104,
      110,  111,  111,  108,  203,  194,  109,   43,   48,  109,
      145,  195,  112,  110,  111,  111,   43,   46,   47,   47,
      146,  130,  109,  131,  410,  112,   46,   47,   47,   48,
      113,  113,  114,  114,  116,  158,  132,  133,   48,  116,
      159,  117,  117,  117,  118,  118,   52,   52,   52,  118,
      118,  409,  408,  407,  116,   62,  119,  119,  120,  120,
       62,  118,  118,  118,  118,  118,  198,  115,  118,  118,

      118,  118,  118,   60,  199,   62,   70,   70,   70,   70,
       61,   61,   61,   61,   61,   73,   73,   73,   73,   73,
      406,   72,   72,  121,   62,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,  138,  161,  165,  139,  186,
      405,  170,  162,  187,  109,  207,  170,  404,  166,  109,
      163,  110,  111,  111,  208,  403,  110,  111,  111,  170,
      109,  402,  109,  112,   43,  109,  401,  300,  112,  110,
      111,  111,  400,  399,  176,  177,  177,  178,  109,   43,
      398,  112,   42,  301,  172,  397,   48,  107,  396,  179,
      180,  180,  181,  395,  173,  173,  174,  174,  394,  225,

      226,   48,  170,  107,  227,  109,  107,  393,  392,  116,
      107,  107,  110,  111,  111,  107,  183,  183,  183,  183,
      391,  109,  107,  186,  112,  116,  107,  413,  107,  390,
      107,  175,   52,   52,   52,  118,  118,  118,  118,  118,
      118,  118,  389,  388,  387,  116,   62,  170,  386,  385,
      109,   62,  184,  184,  184,  184,  384,  237,  238,  238,
      239,  170,  383,  382,  109,   43,  109,  381,  380,  112,
      379,  240,  241,  241,  242,  179,  180,  180,  181,   43,
      109,  378,  377,  112,  171,  376,  375,   48,  374,  179,
      180,  180,  181,  373,  243,  243,  243,  243,  243,  372,

      371,   48,  370,  369,  368,  367,   43,  366,  365,  364,
      243,  243,  243,  243,  243,  243,  179,  180,  180,  181,
       43,  363,  362,   43,  361,  360,   43,  359,   48,  358,
       46,   47,   47,   46,   47,   47,   46,   47,   47,  357,
      356,  355,   48,  116,   43,   48,  354,  353,   48,   43,
      184,  184,  184,  184,   46,   47,   47,  352,  351,  244,
      245,  245,  246,  246,  350,  349,   48,  348,  347,  346,
      345,   48,  344,  343,  342,  246,  246,  246,  246,  246,
      246,  170,  341,  340,  109,  170,  339,  338,  109,  337,
      336,  240,  241,  241,  242,  240,  241,  241,  242,  170,

      109,  335,  109,  112,  109,  170,  334,  112,  109,  240,
      241,  241,  242,  333,  332,  110,  111,  111,  109,  170,
      331,  112,  109,  170,  109,  330,  109,  112,  329,  110,
      111,  111,  328,  110,  111,  111,  327,  326,  109,  325,
       43,  112,  109,  324,  323,  112,  170,  322,  321,  109,
       46,   47,   47,  320,  319,  318,  290,  291,  291,  292,
      292,  317,   48,  316,  315,  109,  314,  313,  112,   43,
      312,  311,  292,  292,  292,  292,  292,  292,  310,   46,
       47,   47,  170,  309,  308,  109,  170,  307,  306,  109,
      305,   48,  110,  111,  111,  304,  110,  111,  111,  170,

      303,  109,  109,  302,  112,  109,  299,  298,  112,  110,
      111,  111,  297,  296,  295,  294,  293,  116,  109,  289,
      288,  112,   42,  287,   42,  286,   42,   42,  285,   42,
       42,   42,   49,  284,  283,  282,   49,   49,  281,   49,
       49,   49,   74,   74,  280,  279,   74,   74,  107,  278,
      107,  107,  107,  107,  107,  107,  107,  107,   42,   42,
       42,   42,  277,   42,   42,  276,   42,   49,   49,   49,
      275,   49,   49,  274,   49,  122,  122,  122,  122,  122,
      122,  122,  122,  122,  122,  124,  124,  124,  124,  124,
      124,  124,  124,  124,  124,  126,  126,  109,  273,  109,

      109,  109,  109,  109,  109,  109,  109,  182,  182,  185,
      185,  188,  188,  247,  247,  247,  272,  271,  270,  269,
      268,  267,  266,  265,  264,  263,  262,  261,  260,  259,
      258,  257,  256,  255,  254,  253,  252,  251,  250,  249,
      248,  116,  116,  171,  171,  236,  235,  234,  233,  232,
      231,  230,  229,  228,  224,  223,  222,  221,  220,  219,
      218,  217,  216,  215,  214,  213,  212,  211,  210,  209,
      206,  205,  204,  201,  200,  197,  196,  193,  192,  191,
      190,  189,  125,  125,  123,  171,  171,  169,  168,  167,
      164,  160,  155,  154,  153,  152,  151,  150,  149,  148,

      147,  144,  143,  142,  141,  140,  135,  134,  129,  128,
      127,  125,  123,  116,  106,  105,  101,   97,   92,   91,
       90,   82,   77,   68,   65,   56,   55,   54,   41,  413,
        3,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413
    } ;

static yyconst short int yy_chk[886] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    8,   10,   10,   10,   10,   10,
       98,   98,    8,    8,    8,    8,    8,   10,   15,   17,
       16,   17,   15,   19,   33,   19,    8,   16,   16,   16,
       16,   16,   33,  411,  409,   15,   21,   21,   21,   21,
       21,   16,   22,   22,   24,   26,   22,   22,   22,   22,

       22,   28,   28,   36,   28,   26,   29,   34,   26,   28,
       24,   81,   34,   28,   26,   81,   42,   29,  138,   36,
       44,   38,   36,   44,   21,   38,   42,   42,   42,   38,
       44,   44,   44,   45,  138,  132,   45,   46,   42,   44,
       88,  132,   44,   45,   45,   45,   47,   46,   46,   46,
       88,   78,   45,   78,  405,   45,   47,   47,   47,   46,
       48,   48,   48,   48,   50,   99,   78,   78,   47,   51,
       99,   50,   50,   50,   50,   50,   51,   51,   51,   51,
       51,  404,  403,  399,   52,   50,   53,   53,   53,   53,
       51,   52,   52,   52,   52,   52,  135,   48,   60,   60,

       60,   60,   60,   61,  135,   52,   70,   70,   70,   70,
       61,   61,   61,   61,   61,   72,   72,   72,   72,   72,
      398,   62,   62,   53,   61,   62,   62,   62,   62,   62,
       73,   73,   73,   73,   73,   82,  101,  103,   82,  123,
      396,  107,  101,  123,  107,  142,  110,  395,  103,  110,
      101,  107,  107,  107,  142,  394,  110,  110,  110,  111,
      107,  393,  111,  107,  113,  110,  392,  257,  110,  111,
      111,  111,  391,  390,  113,  113,  113,  113,  111,  114,
      389,  111,  112,  257,  112,  387,  113,  112,  384,  114,
      114,  114,  114,  381,  112,  112,  112,  112,  380,  159,

      159,  114,  172,  112,  159,  172,  112,  376,  375,  119,
      112,  112,  172,  172,  172,  112,  119,  119,  119,  119,
      371,  172,  112,  186,  172,  117,  112,  186,  112,  370,
      112,  112,  117,  117,  117,  117,  117,  118,  118,  118,
      118,  118,  369,  368,  363,  120,  117,  173,  362,  361,
      173,  118,  120,  120,  120,  120,  360,  173,  173,  173,
      173,  174,  359,  357,  174,  176,  173,  356,  353,  173,
      352,  174,  174,  174,  174,  176,  176,  176,  176,  177,
      174,  351,  350,  174,  175,  348,  345,  176,  344,  177,
      177,  177,  177,  343,  175,  175,  175,  175,  175,  341,

      340,  177,  339,  338,  337,  336,  178,  335,  334,  333,
      175,  175,  175,  175,  175,  175,  178,  178,  178,  178,
      179,  332,  331,  180,  330,  329,  181,  327,  178,  326,
      179,  179,  179,  180,  180,  180,  181,  181,  181,  325,
      324,  322,  179,  183,  244,  180,  321,  320,  181,  182,
      183,  183,  183,  183,  244,  244,  244,  319,  317,  182,
      182,  182,  182,  182,  316,  315,  244,  314,  313,  312,
      311,  182,  310,  308,  307,  182,  182,  182,  182,  182,
      182,  237,  306,  305,  237,  238,  304,  301,  238,  300,
      299,  237,  237,  237,  237,  238,  238,  238,  238,  239,

      237,  298,  239,  237,  238,  240,  296,  238,  240,  239,
      239,  239,  239,  295,  294,  240,  240,  240,  239,  241,
      293,  239,  241,  242,  240,  289,  242,  240,  288,  241,
      241,  241,  286,  242,  242,  242,  285,  284,  241,  283,
      245,  241,  242,  282,  281,  242,  243,  280,  279,  243,
      245,  245,  245,  278,  277,  275,  243,  243,  243,  243,
      243,  274,  245,  272,  271,  243,  270,  269,  243,  246,
      268,  267,  243,  243,  243,  243,  243,  243,  266,  246,
      246,  246,  290,  265,  264,  290,  291,  263,  262,  291,
      261,  246,  290,  290,  290,  260,  291,  291,  291,  292,

      259,  290,  292,  258,  290,  291,  256,  253,  291,  292,
      292,  292,  252,  251,  250,  249,  248,  247,  292,  236,
      233,  292,  414,  232,  414,  231,  414,  414,  230,  414,
      414,  414,  415,  228,  227,  226,  415,  415,  225,  415,
      415,  415,  416,  416,  224,  222,  416,  416,  417,  220,
      417,  417,  417,  417,  417,  417,  417,  417,  418,  418,
      418,  418,  219,  418,  418,  218,  418,  419,  419,  419,
      217,  419,  419,  216,  419,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  422,  422,  423,  215,  423,

      423,  423,  423,  423,  423,  423,  423,  424,  424,  425,
      425,  426,  426,  427,  427,  427,  214,  213,  212,  211,
      210,  209,  208,  207,  206,  205,  204,  203,  202,  201,
      200,  199,  198,  197,  195,  194,  193,  192,  191,  190,
      189,  185,  184,  171,  170,  169,  168,  167,  166,  164,
      163,  162,  161,  160,  158,  157,  156,  155,  154,  153,
      152,  151,  150,  149,  148,  147,  146,  145,  144,  143,
      141,  140,  139,  137,  136,  134,  133,  131,  130,  129,
      128,  127,  125,  124,  122,  109,  108,  106,  105,  104,
      102,  100,   97,   96,   95,   94,   93,   92,   91,   90,

       89,   87,   86,   85,   84,   83,   80,   79,   77,   76,
       75,   58,   57,   49,   40,   39,   37,   35,   32,   31,
       30,   27,   25,   20,   18,   14,   13,   12,    7,    3,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413,  413,  413,  413,  413,  413,
      413,  413,  413,  413,  413
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 ".\\moronico.l"
#define INITIAL 0
#line 2 ".\\moronico.l"
#include <stdio.h>
#include "moronico.tab.h"


/*Macros de apoyo */
/*Macros usadas en las reglas*/
/*Opcion para no ser sensible a minusculas y mayusulas. ?i:reg-ex no funciona en mi version*/
#line 768 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 60 ".\\moronico.l"


  /*Palabras reservadas*/
#line 923 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 414 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 831 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 63 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return ABSTRACTO; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 64 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return ASOCIATIVA; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 65 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return BOOLEANO; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 66 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return CABECERA; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 67 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return CADENA; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 68 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return CASO; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 69 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return CARACTER; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 70 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return CLASE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 71 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return CONJUNTO; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 72 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return CONSTANTE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 73 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return CUERPO; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 74 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return CONSTRUCTOR; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 75 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return CUANDO; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 76 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return DESCENDENTE; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 77 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return DESTRUCTOR; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 78 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return DE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 79 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return DEVOLVER; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 80 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return CARGA; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 81 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return ELEMENTO; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 82 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return EJECUTA; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 83 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return EN; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 84 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return ENTERO; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 85 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return ENTONCES; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 86 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return ESPECIFICO; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 87 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return EXCEPTO; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 88 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return FICHERO; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 89 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return FINAL; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 90 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return FINALMENTE; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 91 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return FUNCION; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 92 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return GENERICO; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 93 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return HASTA; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 94 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return INTERFAZ; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 95 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return LANZAR; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 96 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return LISTA; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 97 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return MIENTRAS; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 98 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return MODIFICABLE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 99 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return OTRO; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 100 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return PAQUETE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 101 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return PARA; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 102 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return PRIVADO; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 103 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return PROBAR; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 104 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return PROCEDIMIENTO; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 105 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return PROGRAMA; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 106 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return PUBLICO; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 107 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return REAL; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 108 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return REGISTRO; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 109 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return REPITE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 110 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return SALIR; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 111 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return SEA; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 112 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return SEMIPUBLICO; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 113 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return SI; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 114 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return SINO; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 115 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return TIPO; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 116 ".\\moronico.l"
{ printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return VARIABLE; }
	YY_BREAK
/*Identificadores*/
case 55:
YY_RULE_SETUP
#line 119 ".\\moronico.l"
{ printf("linea %d, identificador: %s\n", yylineno, yytext); return IDENTIFICADOR; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 122 ".\\moronico.l"
{ printf("linea %d, PATH: %s\n", yylineno, yytext); return PATH; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 123 ".\\moronico.l"
{ printf("linea %d, constante entera: %s\n", yylineno, yytext); return CTC_ENTERA; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 124 ".\\moronico.l"
{ printf("linea %d, constante real: %s\n", yylineno, yytext); return CTC_REAL; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 125 ".\\moronico.l"
{ printf("linea %d, caracter: %s\n", yylineno, yytext); return CTC_CARACTER; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 126 ".\\moronico.l"
{ printf("linea %d, cadena: %s\n", yylineno, yytext); return CTC_CADENA; }
	YY_BREAK
/*En el caso de los delimitadores de un unico caracter se devuelve el mismo caracter*/
case 61:
YY_RULE_SETUP
#line 129 ".\\moronico.l"
{ printf("linea %d, delimitador: %s\n", yylineno, yytext); return yytext[0]; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 130 ".\\moronico.l"
{ printf("linea %d, delimitador: %s\n", yylineno, yytext); return CUATRO_PTOS; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 131 ".\\moronico.l"
{ printf("linea %d, delimitador: %s\n", yylineno, yytext); return DOS_PTOS; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 132 ".\\moronico.l"
{ printf("linea %d, delimitador: %s\n", yylineno, yytext); return FLECHA_DOBLE; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 135 ".\\moronico.l"
{ printf("linea %d, operador: %s\n", yylineno, yytext); return yytext[0]; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 136 ".\\moronico.l"
{ printf("linea %d, operador: %s\n", yylineno, yytext); return POTENCIA; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 137 ".\\moronico.l"
{ printf("linea %d, operador: %s\n", yylineno, yytext); return DESPI; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 138 ".\\moronico.l"
{ printf("linea %d, operador: %s\n", yylineno, yytext); return DESPD; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 139 ".\\moronico.l"
{ printf("linea %d, operador: %s\n", yylineno, yytext); return EQ; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 140 ".\\moronico.l"
{ printf("linea %d, operador: %s\n", yylineno, yytext); return GEQ; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 141 ".\\moronico.l"
{ printf("linea %d, operador: %s\n", yylineno, yytext); return LEQ; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 142 ".\\moronico.l"
{ printf("linea %d, operador: %s\n", yylineno, yytext); return NEQ; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 143 ".\\moronico.l"
{ printf("linea %d, operador: %s\n", yylineno, yytext); return OR; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 144 ".\\moronico.l"
{ printf("linea %d, operador: %s\n", yylineno, yytext); return AND; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 147 ".\\moronico.l"
{}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 148 ".\\moronico.l"
{}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 151 ".\\moronico.l"
{}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 155 ".\\moronico.l"
{ printf ("Error en la linea %d, caracter no reconocido %s\n", yylineno, yytext); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 158 ".\\moronico.l"
ECHO;
	YY_BREAK
#line 1411 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 414 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 414 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 413);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 158 ".\\moronico.l"


